data_mart:
  target: dev-mysql
  outputs:
    dev-mysql:
      type: mysql
      server: hangrytest-hangrytest.h.aivencloud.com
      port: 21843  # optional
      database: staging # optional, should be same as schema
      schema: staging
      username: avnadmin
      password: "{{ env_var('MYSQL_PASS') }}"
      driver: MySQL ODBC 8.0 ANSI Driver
    dev-sqlite:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: 'staging.db'
      schema_directory: './'
